server:
  port: 8080

spring:
  datasource:
    username: root
    password: 231816
    url: jdbc:mysql://127.0.0.1:3306/gateway?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml